### ISSUE TITLE
[Issue]: build fails to non-existing llvm path

### ISSUE THREAD

**Issue by jdgh000** [ROCm/clr#85]
### Problem Description

Tried building hipamd in clr but failing because LLVM_DIR is apparently wrongly set or not set:
From clr/hipamd
mkdir build
cd build
cmake ..

./..'
+ /usr/lib64/cmake/llvm/../../../bin/clang -O3 --hip-path=/home/nonroot/build-install-scripts/rocm/ROCm-6.1/clr/hipamd/build/include/.. -std=c++17 -nogpulib -isystem /home/nonroot/build-install-scripts/rocm/ROCm-6.1/clr/hipamd/build/include -isystem /include -isystem /home/nonroot/build-install-scripts/rocm/ROCm-6.1/clr/hipamd/include --cuda-device-only --cuda-gpu-arch=gfx1030 -x hip /tmp/hip_pch.3610/hip_pch.h -E
/home/nonroot/build-install-scripts/rocm/ROCm-6.1/clr/hipamd/src/hip_embed_pch.sh: line 148: /usr/lib64/cmake/llvm/../../../bin/clang: No such file or directory

in that script file called hip_embed_pch.sh, the path is set in $LLVM_DIR/bin/clang which itself seems to be called from main CMakeLists.txt. 

hip_embed_pch.sh USAGE:
echo "Usage: $(basename "$0") HIP_BUILD_INC_DIR HIP_INC_DIR HIP_AMD_INC_DIR LLVM_DIR [option] [RTC_LIB_OUTPUT]"

This is called from cmake as:
183:  execute_process(COMMAND sh -c "${CMAKE_CURRENT_SOURCE_DIR}/hip_embed_pch.sh \
${HIP_COMMON_INCLUDE_DIR} \
${PROJECT_BINARY_DIR}/include \
${PROJECT_SOURCE_DIR}/include \
${HIP_LLVM_ROOT}" \
COMMAND_ECHO STDERR RESULT_VARIABLE EMBED_PCH_RC WORKING_DIRECTORY ${CMAKE_BINARY_DIR})
set(HIP_LLVM_ROOT "${LLVM_DIR}/../../..")

HIP_LLVM_ROOT is defined here in same cmake:
179:  if(NOT DEFINED HIP_LLVM_ROOT)
180:    set(HIP_LLVM_ROOT "${LLVM_DIR}/../../..")
but it is unclear what LLVM_DIR should be, by default path of rocm installation, it seems LLVM_DIR=/opt/rocm-6.1.0/llvm which I could pass on to cmake as env param but going back three folders up will land in / which is not going to work. 

OS:
NAME="CentOS Stream"
VERSION="9"
CPU:
model name      : Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
GPU:
  Name:                    Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
  Marketing Name:          Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
  Name:                    Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
  Marketing Name:          Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
  Name:                    gfx908
  Marketing Name:          AMD Instinct MI100
      Name:                    amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-
  Name:                    gfx908
  Marketing Name:          AMD Instinct MI100
      Name:                    amdgcn-amd-amdhsa--gfx908:sramecc+:xnack-

### Operating System

Centos 9

### CPU

Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.1.0

### ROCm Component

clr

### Steps to Reproduce

from clr/hipamd/ ; mkdir build ; cd build

**Comment by iassiour** [comment]
Hi @jdgh000 I think there should be a /opt/rocm/llvm/**lib/cmake/llvm** and find_package normally returns that as LLVM_DIR. 
Then HIP_CLANG_ROOT is set to  /opt/rocm/llvm. 
But it looks like that folder is missing from your installation and find_package returns the system one /usr/lib64/cmake/llvm instead.
I think you probably need to additionally install the rocm-llvm-dev package. This will add the missing directories under /opt/rocm/llvm

**Comment by jdgh000** [comment]
i am not understanding your evaluation at all and makes no sense at all!?. I already mentioned where it is having error in my original description. 
It is looking for clang nothing else which is installed as evidently seen in : 
/home/nonroot/build-install-scripts/rocm/ROCm-6.1/clr/hipamd/src/hip_embed_pch.sh: line 148: /usr/lib64/cmake/llvm/../../../bin/clang: No such file or directory

Regardless, llvm-devel installed with no expectation it will solve and after installation, you were wrong, and I was right, it made no difference.

**Comment by iassiour** [comment]
Hi @jdgh000, LLVM_DIR is a  cache variable set by cmake find_package call here:
https://github.com/ROCm/clr/blob/develop/hipamd/src/CMakeLists.txt#L182

In the find_package call, the PATHS is set to ${ROCM_PATH}/llvm. That means it is expected that the config file is found under /opt/rocm. In that case LLVM_DIR would be set to /opt/rocm/llvm/lib64/cmake/llvm and HIP_LLVM_ROOT,  (the argument passed to the script hip_embed_pch.sh) points to  /opt/rocm/llvm which would make sense.

A note that the above LLVM_DIR cmake variable is not to be confused with the 4th parameter LLVM_DIR that is used in hip_embed_pch.sh and that is actually the HIP_LLVM_ROOT.

In your case find_package(LLVM) instead of returning the llvm configuration under /opt/rocm it returns one found in /usr
/usr/lib64/cmake/llvm. I think that is not expected and is likely the root cause of the problem as it leads to invalid paths later on. 

After installing rocm-llvm-dev can you please confirm that  /opt/rocm/llvm/lib/cmake/llvm or (/opt/rocm/llvm/**lib64**/cmake/llvm) exists on your machine. If it exists please try again with a clean cmake build (LLVM_DIR is a cache variable)

PS. I think the find_package call here https://github.com/ROCm/clr/blob/develop/hipamd/src/CMakeLists.txt#L182 
should have set the NO_DEFAULT_PATH to ignore config files found in system paths like /usr and return only what is found under /opt/rocm.

**Comment by jdgh000** [comment]
I actually refer back to build instruction for clr. instead of trying to build from hipamd. But same error occurs in cmake stage. 
I dont believe it is my job to go into deep debugging session, i think it should be yours to investigate if users can not build following the instruction published: 
Stuff you are talking about LLVM_ROOT and other dirs are unfortunately not mentioned in the instruction:


**Linux**
Clone this repository
cd clr && mkdir build && cd build
For HIP : cmake .. -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=$HIP_COMMON_DIR
HIP_COMMON_DIR points to [HIP](https://github.com/ROCm/HIP)
HIPCC_BIN_DIR points to [HIPCC](https://github.com/ROCm/HIPCC)'s bin folder. If not provided, it defaults to /opt/rocm/bin.
For OpenCL™ : cmake .. -DCLR_BUILD_OCL=ON
make : to build
make install : to install

**Comment by jdgh000** [comment]
do we have update here?

**Comment by iassiour** [comment]
Hi @jdgh000  can you modify your cmake command to this and confirm if it works:
cmake .. **-DCMAKE_PREFIX_PATH="/opt/rocm/"** -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=/home/nonroot/git/HIP

In that case I will follow-up with a fix as setting the CMAKE_PREFIX_PATH should not be required, as per the published instructions.

**Comment by jdgh000** [comment]
this appears working however this time, getting another error about max vs. fmax in header:
To erase compaibility issues, i reinstalled rocm6.0 and checkout rocm-6.0.x branch of both HIP and clr and still occurs. 

-- Found OpenGL: /usr/lib64/libOpenGL.so
-- HIPCC_BIN_DIR found at /opt/rocm/bin
-- HIP_COMMON_DIR found at /home/nonroot/git/HIP
-- HIPNV_DIR found at
-- Found Perl: /usr/bin/perl (found version "5.32.1")
CMake Error at hipamd/CMakeLists.txt:87 (file):
  file STRINGS file "/home/nonroot/git/HIP/VERSION" cannot be read.


-- Found Git: /usr/bin/git (found version "2.43.0")
-- Using CPACK_DEBIAN_PACKAGE_RELEASE local
-- CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- HIP Platform: amd
-- HIP Runtime: rocclr
-- HIP Compiler: clang
-- ROCM Installation path(ROCM_PATH): /opt/rocm
-- HIP will be installed in: /opt/rocm
-- Could NOT find Terminfo (missing: Terminfo_LIBRARIES Terminfo_LINKABLE)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Found zstd: /usr/lib64/libzstd.so
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.13")
'sh' '-c' '/root/extdir/gg/git/clr/hipamd/src/hip_embed_pch.sh /home/nonroot/git/HIP/include /root/extdir/gg/git/clr/build/hipamd/include /root/extdir/gg/git/clr/hipamd/include /opt/rocm/llvm/lib/cmake/llvm/../../..'
+ /opt/rocm/llvm/lib/cmake/llvm/../../../bin/clang -O3 --rocm-path=/root/extdir/gg/git/clr/build/hipamd/include/.. -std=c++17 -nogpulib -isystem /root/extdir/gg/git/clr/build/hipamd/include -isystem /root/extdir/gg/git/HIP/include -isystem /root/extdir/gg/git/clr/hipamd/include --cuda-device-only --cuda-gpu-arch=gfx1030 -x hip /tmp/hip_pch.237/hip_pch.h -E
+ cat /tmp/hip_pch.237/hip_macros.h
+ /opt/rocm/llvm/lib/cmake/llvm/../../../bin/clang -cc1 -O3 -emit-pch -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -fcuda-is-device -std=c++17 -fgnuc-version=4.2.1 -o /tmp/hip_pch.237/hip_wave32.pch -x hip-cpp-output -
In file included from /tmp/hip_pch.237/hip_pch.h:1:
In file included from /root/extdir/gg/git/HIP/include/hip/hip_runtime.h:62:
In file included from /root/extdir/gg/git/clr/hipamd/include/hip/amd_detail/amd_hip_runtime.h:432:
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_complex_builtins.h:194:30: error: use of undeclared identifier 'max'; did you mean 'fmax'?
  double __logbw = std::logb(max(std::abs(__c), std::abs(__d)));
                             ^
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_math_forward_declares.h:73:81: note: 'fmax' declared here
static __inline__ __attribute__((always_inline)) __attribute__((device)) double fmax(double, double);
                                                                                ^
In file included from /tmp/hip_pch.237/hip_pch.h:1:
In file included from /root/extdir/gg/git/HIP/include/hip/hip_runtime.h:62:
In file included from /root/extdir/gg/git/clr/hipamd/include/hip/amd_detail/amd_hip_runtime.h:432:
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_complex_builtins.h:227:29: error: use of undeclared identifier 'max'; did you mean 'fmax'?
  float __logbw = std::logb(max(std::abs(__c), std::abs(__d)));
                            ^
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_math_forward_declares.h:74:80: note: 'fmax' declared here
static __inline__ __attribute__((always_inline)) __attribute__((device)) float fmax(float, float);
                                                                               ^
2 errors generated when compiling for .
CMake Error at hipamd/src/CMakeLists.txt:182 (message):
  Failed to embed PCH

**Comment by iassiour** [comment]
I think that the cause for the max vs. fmax error is this:

```
CMake Error at hipamd/CMakeLists.txt:87 (file):
file STRINGS file "/home/nonroot/git/HIP/VERSION" cannot be read.
```
Please double check that the path exists and the file permissions are correct.

**Comment by jdgh000** [comment]
the file is there, it is unclear how it is resulting, i checkoud HIP as is, no modification done whatsoever but it can not process it:
cat ../../HIP/VERSION
#HIP_VERSION_MAJOR
6
#HIP_VERSION_MINOR
0
#HIP_VERSION_PATCH
32831

[root@localhost build]# cat ../hipamd/CMakeLists.txt  | grep -n VERSION | grep ^87:
87:file(STRINGS ${HIP_COMMON_DIR}/VERSION VERSION_LIST REGEX "^[0-9]+")

**Comment by jdgh000** [comment]
are you checking on your end? I am just wondering/surprised why kept thinking this is my environment and check this. This is clearly the issue with your end. 
For example, you mention "Please double check that the path to the VERSION file exists and the permissions are correct." but this how it is checkout from your repository snapshot and build fails.

**Comment by iassiour** [comment]
If the file is checkout as it is from the repo, with no modifications, it should work. I can't reproduce the issue on my end.

_cmake --version
cmake version 3.22.1_

**Comment by jdgh000** [comment]
I have hard time relating what you are saying. I already provided logs and version and you still arguing against facts that it should work. What do you mean by that?
"I can't reproduce the issue on my end". This is soooo simple, you just checkout and build using instruction and easily reproducible. What steps did you take? What O/S and rocm version did you use?

- Another surpirse is I saw the version file error which I you led me to believe it is causing disrepancy of max vs. fmax. YOu did not provide any rationale response about why it occurs. For me, it makes no sense the failure to read VERSION causing max/fmax error. 
-

**Comment by iassiour** [comment]
Hi @jdgh000,

> Another surprise is I saw the version file error which I you led me to believe it is causing disrepancy of max vs. fmax. YOu did not provide any rationale response about why it occurs. For me, it makes no sense the failure to read VERSION causing max/fmax error.

cmake generates a file hip_version.h under the clr build directory that adds definitions based on the information read from the VERSION file. For example:

```
#define HIP_VERSION_MAJOR 6
#define HIP_VERSION_MINOR 0
#define HIP_VERSION_PATCH 32831
```

hip_version.h is then used by clang  to setup the right include files for the hip version you are trying to build, among other places this file is being used.  
If the version information is missing or is wrong, many compatibility issues can come up and the max vs fmax error we are seeing is one of them. 
 
I am using Ubuntu 22.04.3, rocm 6.0, cmake version 3.22.1

```
git clone -b rocm-6.0.x https://github.com/ROCm/clr.git
git clone -b rocm-6.0.x https://github.com/ROCm/HIP.git
cd clr && mkdir build && cd build
cmake .. -DCMAKE_PREFIX_PATH="/opt/rocm/" -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR="/home/iassiour/HIP"
make
```

Following the steps above, I do not get the _file VERSION cannot be read error_ and the configuration plus build runs successfully.
A note that I am checking out the rocm-6.0.x branch of clr/HIP but makes no difference for me if I use the develop branches and the latest rocm version.

**Comment by jdgh000** [comment]
i installed rocm6.0 on ubntu 22.04 but it says missing file make.in but it is  there:

```
CMake Error at hipamd/CMakeLists.txt:87 (file):
  file STRINGS file
  "~/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//VERSION"
  cannot be read.


-- Using CPACK_DEBIAN_PACKAGE_RELEASE local
-- CPACK_RPM_PACKAGE_RELEASE: local
-- HIP Platform: amd
-- HIP Runtime: rocclr
-- HIP Compiler: clang
-- ROCM Installation path(ROCM_PATH): /opt/rocm
-- HIP will be installed in: /opt/rocm
'sh' '-c' '/home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/hipamd/src/hip_embed_pch.sh ~/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//include /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/build/hipamd/include /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/hipamd/include /opt/rocm/llvm/lib/cmake/llvm/../../..'
+ /opt/rocm/llvm/lib/cmake/llvm/../../../bin/clang -O3 --rocm-path=/home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/build/hipamd/include/.. -std=c++17 -nogpulib -isystem /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/build/hipamd/include -isystem /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//include -isystem /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/hipamd/include --cuda-device-only --cuda-gpu-arch=gfx1030 -x hip /tmp/hip_pch.2530/hip_pch.h -E
+ cat /tmp/hip_pch.2530/hip_macros.h
+ /opt/rocm/llvm/lib/cmake/llvm/../../../bin/clang -cc1 -O3 -emit-pch -triple amdgcn-amd-amdhsa -aux-triple x86_64-unknown-linux-gnu -fcuda-is-device -std=c++17 -fgnuc-version=4.2.1 -o /tmp/hip_pch.2530/hip_wave32.pch -x hip-cpp-output -
In file included from /tmp/hip_pch.2530/hip_pch.h:1:
In file included from /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//include/hip/hip_runtime.h:62:
In file included from /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/hipamd/include/hip/amd_detail/amd_hip_runtime.h:432:
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_complex_builtins.h:194:30: error: use of undeclared identifier 'max'; did you mean 'fmax'?
  double __logbw = std::logb(max(std::abs(__c), std::abs(__d)));
                             ^
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_math_forward_declares.h:73:81: note: 'fmax' declared here
static __inline__ __attribute__((always_inline)) __attribute__((device)) double fmax(double, double);
                                                                                ^
In file included from /tmp/hip_pch.2530/hip_pch.h:1:
In file included from /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//include/hip/hip_runtime.h:62:
In file included from /home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/hipamd/include/hip/amd_detail/amd_hip_runtime.h:432:
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_complex_builtins.h:227:29: error: use of undeclared identifier 'max'; did you mean 'fmax'?
  float __logbw = std::logb(max(std::abs(__c), std::abs(__d)));
                            ^
/opt/rocm-6.0.0/lib/llvm/lib/clang/17.0.0/include/__clang_cuda_math_forward_declares.h:74:80: note: 'fmax' declared here
static __inline__ __attribute__((always_inline)) __attribute__((device)) float fmax(float, float);
                                                                               ^
2 errors generated when compiling for .
CMake Error at hipamd/src/CMakeLists.txt:182 (message):
  Failed to embed PCH


-- Configuring incomplete, errors occurred!
See also "/home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/build/CMakeFiles/CMakeOutput.log".
root@localhost:~/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/build# find ~/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/ -name hip-lang-config.cmake.in
/home/nonroot/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP/hip-lang-config.cmake.in
root@localhost:~/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/clr/build# cmake .. -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=~/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP/
```

**Comment by jdgh000** [comment]
Also seeing VERSION read fail randomly, the file is  there but why it is not reading? what should be the permission?
Again, i checked out as is in the repo and did not modify anything.

```

root@localhost:/home/nonroot/git//build-install-scripts/rocm/ROCm-6.0/clr/build# ls -l /home/nonroot/gitcodelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//VERSION                                                                                                    -rw-r--r--. 1 root root 67 Jun 25 05:38 /root/extdir/git/codelab-scripts/build-install-scripts/rocm/ROCm-6.0/HIP//VERSION
root@localhost:/home/nonroot/git//build-install-scripts/rocm/ROCm-6.0/clr/build# cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

```

**Comment by jdgh000** [comment]
let me look at it and come back!

**Comment by tcgu-amd** [comment]
@jdgh000 Any updates? Thanks!

**Comment by jdgh000** [comment]
I am not seeing clearing the build directory fixes anything, I just retried:
```

sudo cmake -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=$HIP_COMMON_DIR=../../HIP  ..
-- The C compiler identification is GNU 11.5.0
-- The CXX compiler identification is GNU 11.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- HIPCC Binary Directory: /opt/rocm/bin
-- HIP Common Directory: =../../HIP
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found AMD_OPENCL: /root/rocm/ROCm-6.2/clr/opencl/khronos/headers/opencl2.2/CL
CMake Error at rocclr/cmake/ROCclrLC.cmake:37 (file):
  file STRINGS file
  "/root/rocm/ROCm-6.2/clr/rocclr/=../../HIP/VERSION"
  cannot be read.
Call Stack (most recent call first):
  rocclr/cmake/ROCclr.cmake:139 (include)
  rocclr/CMakeLists.txt:30 (include)


-- Found NUMA: /usr/lib64/libnuma.so
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- HIPCC_BIN_DIR found at /opt/rocm/bin
-- HIP_COMMON_DIR found at =../../HIP
-- HIPNV_DIR found at
-- Found Perl: /bin/perl (found version "5.32.1")
CMake Error at hipamd/CMakeLists.txt:88 (file):
  file STRINGS file
  "/root/rocm/ROCm-6.2/clr/hipamd/=../../HIP/VERSION"
  cannot be read.


-- Found Git: /bin/git (found version "2.43.5")
-- Using CPACK_DEBIAN_PACKAGE_RELEASE local
-- CPACK_RPM_PACKAGE_RELEASE: local%{?dist}
-- HIP Platform: amd
-- HIP Runtime: rocclr
-- HIP Compiler: clang
-- ROCM Installation path(ROCM_PATH): /opt/rocm
-- HIP will be installed in: /opt/rocm
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib64/libtinfo.so
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.3.#define ZLIB_VERSION "1.3"")
-- Found zstd: /usr/local/lib64/libzstd.so
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.13")
'sh' '-c' '/root/rocm/ROCm-6.2/clr/hipamd/src/hip_embed_pch.sh =../../HIP/include /root/rocm/ROCm-6.2/clr/build/hipamd/include /root/rocm/ROCm-6.2/clr/hipamd/include /opt/rocm/llvm/lib/cmake/llvm/../../..'
+ /opt/rocm/llvm/lib/cmake/llvm/../../../bin/clang -O3 --hip-path=/root/rocm/ROCm-6.2/clr/build/hipamd/include/.. -std=c++17 -nogpulib -isystem /root/rocm/ROCm-6.2/clr/build/hipamd/include -isystem =../../HIP/include -isystem /root/rocm/ROCm-6.2/clr/hipamd/include --cuda-device-only --cuda-gpu-arch=gfx1030 -x hip /tmp/hip_pch.80988/hip_pch.h -E
/tmp/hip_pch.80988/hip_pch.h:1:10: fatal error: 'hip/hip_runtime.h' file not found
    1 | #include "hip/hip_runtime.h"
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated when compiling for gfx1030.
CMake Error at hipamd/src/CMakeLists.txt:200 (message):
  Failed to embed PCH


-- Configuring incomplete, errors occurred!
[nonroot@SMC-DH144-DC16-U27 build]$  sudo rm -rf ./* ; sudo cmake -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=$HIP_COMMON_DIR=../../HIP  ..^C
[nonroot@SMC-DH144-DC16-U27 build]$ find ../../HIP -name hip_runtime.h
../../HIP/include/hip/hip_runtime.h
[nonroot@SMC-DH144-DC16-U27 build]$ ls -l ../../HIP
total 84
drwxr-xr-x.  2 root root    73 Nov  1 15:34 bin
drwxr-xr-x.  3 root root    54 Nov  1 15:34 cmake
-rw-r--r--.  1 root root    51 Nov  1 15:34 CODEOWNERS
-rw-r--r--.  1 root root     0 Nov  1 15:34 configure
-rw-r--r--.  1 root root  8992 Nov  1 15:34 CONTRIBUTING.md
drwxr-xr-x.  2 root root    90 Nov  1 15:34 docker
drwxr-xr-x. 10 root root  4096 Nov  1 15:34 docs
-rw-r--r--.  1 root root  5271 Nov  1 15:34 hip-lang-config.cmake.in
drwxr-xr-x.  3 root root    25 Nov  1 15:34 include
-rwxr-xr-x.  1 root root  1208 Nov  1 15:34 install.sh
-rw-r--r--.  1 root root 16645 Nov  1 15:34 Jenkinsfile
-rw-r--r--.  1 root root  1080 Nov  1 15:34 LICENSE.txt
-rw-r--r--.  1 root root 11115 Nov  1 15:34 README.md
-rw-r--r--.  1 root root  9833 Nov  1 15:34 RELEASE.md
drwxr-xr-x.  4 root root    42 Nov  1 15:34 util
-rw-r--r--.  1 root root    67 Nov  1 15:34 VERSION

```

**Comment by jdgh000** [comment]
i am just following exactly what the clr page says:
https://github.com/ROCm/clr

    For HIP:

cmake .. -DCLR_BUILD_HIP=ON -DHIP_COMMON_DIR=$HIP_COMMON_DIR

**Comment by tcgu-amd** [comment]
Hi @jdgh000, thanks for the update! I noticed in the log you provided you had

> -DHIP_COMMON_DIR=$HIP_COMMON_DIR=../../HIP

Which seems to be a typo? 

It shows in the subsequent log

```
CMake Error at rocclr/cmake/ROCclrLC.cmake:37 (file):
  file STRINGS file
  "/root/rocm/ROCm-6.2/clr/rocclr/=../../HIP/VERSION
```
Can you try with 

`-DHIP_COMMON_DIR=../../HIP`

and let us know the output? Thanks!

**Comment by tcgu-amd** [comment]
Hi @jdgh000 thanks for the prompt update! Seems like the issue might with using relative path `../../HIP` as your HIP common dir. Can you try using the absolute path to your HIP folder? Thanks!

**Comment by jdgh000** [comment]
after setting abs path, appears to be working
